Repository arduino/arduino-create-agent, pull requests merged in 2020-12, with the labels that each got.

#575 Update status bar icons
  icon/icon_linux.png
  icon/icon_linux_hiber.png
  icon/icon_mac.png
  icon/icon_mac_hiber.png
  icon/icon_mac_light.png
  icon/icon_mac_light_hiber.png
  icon/icon_win.ico
  icon/icon_win_hiber.ico
  icon/icondarwin.go
  icon/iconlinux.go
  icon/iconwin.go
  icon/make_icon.sh
Labels: type:enhancement

#576 revert to building minimum version for mac to 10.9 & separate step fo…
  .github/workflows/release.yml
Labels: CI

#578 CI polishing, add win64, update macOS min version
  .github/workflows/release.yml
  .github/workflows/test.yml
  Taskfile.yml
Labels: CI

#574 add crash-report capabilities
  .github/workflows/release.yml
  .github/workflows/test.yml
  Taskfile.yml
  config.ini
  go.mod
  go.sum
  main.go
  redirect_stderr_unix.go
  redirect_stderr_win.go
  systray/systray.go
  systray/systray_real.go
Labels: type:enhancement

#579 update sytray to latest available version
  go.mod
  go.sum
Labels: dependencies

#580 add virustotal scan to CI release workflow
  .github/workflows/release.yml
Labels: CI

#581 Fix naming inconstistencies
  .github/workflows/release.yml
  systray/systray_real.go
Labels: CI
