Repository arduino/arduino-create-agent, pull requests merged in 2021-12, with the labels that each got.

#680 [skip-changelog] fix and update Close stale issue workflow
  .github/workflows/close-stale-issues.yml
Labels: topic: infrastructure, type: imperfection

#681 Correct key name in "Close stale issues" workflow
  .github/workflows/close-stale-issues.yml
Labels: topic: infrastructure, type: imperfection

#678 bump installbuilder container to the latest version
  .github/workflows/release.yml
Labels: type: enhancement, topic: infrastructure

#683 [skip-changelog] Revert "Pin task version in workflows running on windows (#677)"
  .github/workflows/publish-go-tester-task.yml
  .github/workflows/release.yml
  .github/workflows/test-go-integration-task.yml
  .github/workflows/test-go-task.yml
Labels: type: enhancement, os: windows, topic: infrastructure

#686 Use major version ref of `carlosperate/download-file-action`
  .github/workflows/sync-labels.yml
Labels: type: enhancement, topic: infrastructure
