Repository arduino/arduino-create-agent, pull requests merged in 2021-02, with the labels that each got.

#591 [EDITOR-527] E2E testing infrastructure
  .github/workflows/release.yml
  .github/workflows/test.yml
  .gitignore
  Taskfile.yml
  poetry.lock
  pyproject.toml
  test/conftest.py
  test/test_certs.py
  test/test_info.py
  test/test_update.py
  test/test_v2.py
Labels: type:enhancement

#607 [EDITOR-523] Update README.md
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
Labels: documentation

#613 [EDITOR-503] fix wrong agent version in spotlight [MacOs]
  .github/workflows/release.yml
Labels: CI

#615 [EDITOR-607] add workflow to close stale issues (labeled with waiting for feedback)
  .github/workflows/close-stale-issues.yml
Labels: CI

#616 [EDITOR-621] add port to serial output
  bufferflow_timed.go
  bufferflow_timedraw.go
  serialport.go
Labels: type:enhancement
