Repository arduino/arduino-create-agent, pull requests merged in 2021-03, with the labels that each got.

#617 Add serial discovery support for m1 mac
  go.mod
  go.sum
Labels: dependencies

#624 Add security policy link to readme
  README.md
Labels: priority: medium, topic: documentation, topic: security, type: enhancement

#629 [ATL-1141] Support for wildcard origins
  go.mod
  go.sum
  main.go
Labels: go, type: enhancement
