Repository arduino/arduino-create-agent, pull requests merged in 2023-11, with the labels that each got.

#850 Add new origin to the agent
  main.go
Labels: type: enhancement

#851 Replace mitchellh/go used for macOS notarization
  .github/workflows/release.yml
Labels: type: enhancement, os: macos

#855 Fix installbuilder not able to produce complete artifacts for linux
  .github/workflows/release.yml
Labels: os: linux, type: imperfection

#859 Correct message re: enabling logging
  main.go
Labels: topic: code, type: imperfection

#862 [PNX-354] input sanitization
  home.html
Labels: topic: security
