Repository arduino/arduino-create-agent, pull requests merged in 2023-10, with the labels that each got.

#840 Use SafeJoin in V2 Tools Install endpoint
  main_test.go
  v2/pkgs/tools.go
  v2/pkgs/tools_test.go
Labels: type: enhancement, topic: code, topic: security

#837 fix memory leak
  certificates/install_darwin.go
  systray/exec_darwin.go
Labels: topic: code, type: imperfection

#838 [breaking] Remove indexes v2 endpoint
  .licenses/arduino-create-agent/go/go.bug.st/downloader/v2.dep.yml
  design/pkgs.go
  gen/http/cli/arduino_create_agent/cli.go
  gen/http/indexes/client/cli.go
  gen/http/indexes/client/client.go
  gen/http/indexes/client/encode_decode.go
  gen/http/indexes/client/paths.go
  gen/http/indexes/client/types.go
  gen/http/indexes/server/encode_decode.go
  gen/http/indexes/server/paths.go
  gen/http/indexes/server/server.go
  gen/http/indexes/server/types.go
  gen/http/openapi.json
  gen/http/openapi.yaml
  gen/http/openapi3.json
  gen/http/openapi3.yaml
  gen/indexes/client.go
  gen/indexes/endpoints.go
  gen/indexes/service.go
  gen/indexes/views/view.go
  go.mod
  go.sum
  index/hidefile_default.go
  index/hidefile_windows.go
  index/index.go
  index/index_test.go
  main.go
  main_test.go
  tests/conftest.py
  tools/download.go
  tools/shell_default.go
  tools/shell_windows.go
  tools/tools.go
  v2/http.go
  v2/pkgs/indexes.go
  v2/pkgs/indexes_test.go
  v2/pkgs/tools.go
  v2/pkgs/tools_test.go
Labels: type: enhancement, topic: code, topic: security

#839 Replace deprecated openpgp library
  .licensed.yml
  .licenses/arduino-create-agent/go/github.com/ProtonMail/go-crypto/bitcurves.dep.yml
  .licenses/arduino-create-agent/go/github.com/ProtonMail/go-crypto/brainpool.dep.yml
  .licenses/arduino-create-agent/go/github.com/ProtonMail/go-crypto/eax.dep.yml
  .licenses/arduino-create-agent/go/github.com/ProtonMail/go-crypto/internal/byteutil.dep.yml
  .licenses/arduino-create-agent/go/github.com/ProtonMail/go-crypto/ocb.dep.yml
  .licenses/arduino-create-agent/go/github.com/ProtonMail/go-crypto/openpgp.dep.yml
  .licenses/arduino-create-agent/go/github.com/ProtonMail/go-crypto/openpgp/aes/keywrap.dep.yml
  .licenses/arduino-create-agent/go/github.com/ProtonMail/go-crypto/openpgp/armor.dep.yml
  .licenses/arduino-create-agent/go/github.com/ProtonMail/go-crypto/openpgp/ecdh.dep.yml
  .licenses/arduino-create-agent/go/github.com/ProtonMail/go-crypto/openpgp/ecdsa.dep.yml
  .licenses/arduino-create-agent/go/github.com/ProtonMail/go-crypto/openpgp/eddsa.dep.yml
  .licenses/arduino-create-agent/go/github.com/ProtonMail/go-crypto/openpgp/elgamal.dep.yml
  .licenses/arduino-create-agent/go/github.com/ProtonMail/go-crypto/openpgp/errors.dep.yml
  .licenses/arduino-create-agent/go/github.com/ProtonMail/go-crypto/openpgp/internal/algorithm.dep.yml
  .licenses/arduino-create-agent/go/github.com/ProtonMail/go-crypto/openpgp/internal/ecc.dep.yml
  .licenses/arduino-create-agent/go/github.com/ProtonMail/go-crypto/openpgp/internal/encoding.dep.yml
  .licenses/arduino-create-agent/go/github.com/ProtonMail/go-crypto/openpgp/packet.dep.yml
  .licenses/arduino-create-agent/go/github.com/ProtonMail/go-crypto/openpgp/s2k.dep.yml
  .licenses/arduino-create-agent/go/github.com/cloudflare/circl/dh/x25519.dep.yml
  .licenses/arduino-create-agent/go/github.com/cloudflare/circl/dh/x448.dep.yml
  .licenses/arduino-create-agent/go/github.com/cloudflare/circl/ecc/goldilocks.dep.yml
  .licenses/arduino-create-agent/go/github.com/cloudflare/circl/internal/conv.dep.yml
  .licenses/arduino-create-agent/go/github.com/cloudflare/circl/internal/sha3.dep.yml
  .licenses/arduino-create-agent/go/github.com/cloudflare/circl/math.dep.yml
  .licenses/arduino-create-agent/go/github.com/cloudflare/circl/math/fp25519.dep.yml
  .licenses/arduino-create-agent/go/github.com/cloudflare/circl/math/fp448.dep.yml
  .licenses/arduino-create-agent/go/github.com/cloudflare/circl/math/mlsbset.dep.yml
  .licenses/arduino-create-agent/go/github.com/cloudflare/circl/sign.dep.yml
  .licenses/arduino-create-agent/go/github.com/cloudflare/circl/sign/ed25519.dep.yml
  .licenses/arduino-create-agent/go/github.com/cloudflare/circl/sign/ed448.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/crypto/argon2.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/crypto/blake2b.dep.yml
  go.mod
  go.sum
  index/index.go
Labels: type: enhancement, topic: security, topic: infrastructure

#844 Implement HEAD handler for `v2/pkgs/tools/installed` (required by frontend)
  design/pkgs.go
  gen/http/cli/arduino_create_agent/cli.go
  gen/http/openapi.json
  gen/http/openapi.yaml
  gen/http/openapi3.json
  gen/http/openapi3.yaml
  gen/http/tools/client/client.go
  gen/http/tools/client/encode_decode.go
  gen/http/tools/client/paths.go
  gen/http/tools/server/encode_decode.go
  gen/http/tools/server/paths.go
  gen/http/tools/server/server.go
  gen/tools/client.go
  gen/tools/endpoints.go
  gen/tools/service.go
  main_test.go
  v2/pkgs/tools.go
  v2/pkgs/tools_test.go
Labels: type: enhancement, topic: code

#847 fix agent being built for 32 bit linux for real
  .github/workflows/release.yml
Labels: os: linux, topic: infrastructure, type: imperfection
