Repository arduino/arduino-create-agent, pull requests merged in 2023-12, with the labels that each got.

#871 Fix regression showing escaped charaters
  home.html
Labels: type: imperfection

#858 Remove `/certificate.crt` endpoint
  certificates/certificates.go
  main.go
  tests/test_certs.py
Labels: topic: security

#872 Bump GO to version 1.21
  .github/workflows/check-go-dependencies-task.yml
  .github/workflows/check-go-task.yml
  .github/workflows/publish-go-tester-task.yml
  .github/workflows/release.yml
  .github/workflows/test-go-integration-task.yml
  .github/workflows/test-go-task.yml
  go.mod
  go.sum
Labels: type: enhancement

#877 remove unused endpoint
  killbrowser.go
  killbrowser/killbrowser_darwin.go
  killbrowser/killbrowser_linux.go
  killbrowser/killbrowser_windows.go
  main.go
Labels: type: enhancement

#867 Use `codeclysm/extract` and remove custom implementation
  tools/download.go
  tools/download_test.go
  tools/testdata/test_tool_index.json
  utilities/utilities.go
Labels: type: enhancement, topic: security

#878 Remove network upload
  .licenses/arduino-create-agent/go/github.com/kr/fs.dep.yml
  .licenses/arduino-create-agent/go/github.com/miekg/dns.dep.yml
  .licenses/arduino-create-agent/go/github.com/oleksandr/bonjour.dep.yml
  .licenses/arduino-create-agent/go/github.com/pkg/sftp.dep.yml
  .licenses/arduino-create-agent/go/github.com/pkg/sftp/internal/encoding/ssh/filexfer.dep.yml
  .licenses/arduino-create-agent/go/github.com/sfreiberg/simplessh.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/crypto/argon2.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/crypto/blake2b.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/crypto/blowfish.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/crypto/cast5.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/crypto/curve25519.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/crypto/ed25519.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/crypto/sha3.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/crypto/ssh.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/crypto/ssh/agent.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/crypto/ssh/internal/bcrypt_pbkdf.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/net/bpf.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/net/html.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/net/html/atom.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/net/http2.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/net/http2/h2c.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/net/internal/iana.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/net/internal/socket.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/net/ipv4.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/net/ipv6.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/text/internal/language.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/text/internal/language/compact.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/text/internal/tag.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/text/language.dep.yml
  conn.go
  discovery.go
  go.mod
  go.sum
  home.html
  hub.go
  serial.go
  seriallist.go
  serialport.go
  tests/test_ws.py
  upload/README.md
  upload/doc.go
  upload/upload.go
  upload/upload_test.go
Labels: topic: security

#873 Add support to private network CORS
  .licenses/arduino-create-agent/go/github.com/gin-contrib/cors.dep.yml
  .licenses/arduino-create-agent/go/github.com/go-playground/validator/v10.dep.yml
  .licenses/arduino-create-agent/go/github.com/pelletier/go-toml/v2.dep.yml
  .licenses/arduino-create-agent/go/github.com/pelletier/go-toml/v2/internal/characters.dep.yml
  .licenses/arduino-create-agent/go/github.com/pelletier/go-toml/v2/internal/danger.dep.yml
  .licenses/arduino-create-agent/go/github.com/pelletier/go-toml/v2/internal/tracker.dep.yml
  .licenses/arduino-create-agent/go/github.com/pelletier/go-toml/v2/unstable.dep.yml
  go.mod
  go.sum
  main.go
Labels: type: enhancement
