Repository arduino/arduino-create-agent, pull requests merged in 2023-08, with the labels that each got.

#814 Bump go 1.20
  .github/workflows/check-go-dependencies-task.yml
  .github/workflows/check-go-task.yml
  .github/workflows/publish-go-tester-task.yml
  .github/workflows/release.yml
  .github/workflows/test-go-integration-task.yml
  .github/workflows/test-go-task.yml
  .licensed.yml
  .licenses/arduino-create-agent/go/golang.org/x/crypto/curve25519.dep.yml
  go.mod
Labels: type: enhancement, topic: infrastructure

#811 Create `LaunchAgents/` directory if it doesn't exist (MacOS)
  config/autostart.go
Labels: topic: code, os: macos, type: imperfection

#818 Remove io/ioutil since is deprecated
  conn.go
  tools/download.go
  tools/download_test.go
  tools/tools.go
  upload/upload.go
  utilities/utilities.go
  v2/pkgs/indexes.go
  v2/pkgs/indexes_test.go
  v2/pkgs/tools.go
  v2/pkgs/tools_test.go
Labels: topic: code

#813 Download the correct tools for Windows 64-bit
  tools/download.go
  tools/download_test.go
  tools/testdata/test_tool_index.json
  v2/pkgs/pkgs.go
  v2/pkgs/tools.go
Labels: topic: code, os: windows, type: imperfection
