Repository arduino/arduino-create-agent, pull requests merged in 2023-09, with the labels that each got.

#822 Bump actions/checkout to v4
  .github/workflows/check-go-dependencies-task.yml
  .github/workflows/check-go-task.yml
  .github/workflows/check-license.yml
  .github/workflows/publish-go-tester-task.yml
  .github/workflows/release.yml
  .github/workflows/sync-labels.yml
  .github/workflows/test-go-integration-task.yml
  .github/workflows/test-go-task.yml
Labels: topic: infrastructure

#823 [skip-changelog] Add Codecov token
  .github/workflows/test-go-task.yml
Labels: topic: infrastructure

#824 Fix text plain decoding
  design/design.go
  gen/http/openapi.json
  gen/http/openapi.yaml
  main_test.go
  v2/http.go
Labels: topic: code, type: imperfection

#827 Bump Installbuilder to 23.7.0
  .github/workflows/release.yml
Labels: type: enhancement, topic: infrastructure

#830 bugfix: serial enumerator failures in some rare circumstances
  .licenses/arduino-create-agent/go/go.bug.st/serial.dep.yml
  .licenses/arduino-create-agent/go/go.bug.st/serial/enumerator.dep.yml
  .licenses/arduino-create-agent/go/go.bug.st/serial/unixutils.dep.yml
  discovery.go
  go.mod
  go.sum
  main.go
  serial.go
  seriallist.go
  serialport.go
Labels: topic: code, type: imperfection

#821 Use SafeJoin in the uploadHandler
  conn.go
  main_test.go
  utilities/utilities.go
  utilities/utilities_test.go
  v2/pkgs/tools.go
  v2/pkgs/tools_test.go
Labels: topic: code, topic: security, type: imperfection

#826 Add signature verification to V2 tool install endpoint
  conn.go
  design/pkgs.go
  gen/http/cli/arduino_create_agent/cli.go
  gen/http/openapi.json
  gen/http/openapi.yaml
  gen/http/openapi3.json
  gen/http/openapi3.yaml
  gen/http/tools/client/cli.go
  gen/http/tools/client/types.go
  gen/http/tools/server/types.go
  gen/tools/service.go
  globals/globals.go
  main.go
  main_test.go
  utilities/utilities.go
  v2/pkgs/tools.go
Labels: type: enhancement, topic: code, topic: security
