Repository arduino/arduino-create-agent, pull requests merged in 2024-08, with the labels that each got.

#986 Fix agent not able to install `esptool` after 1.6.0
  main_test.go
  tools/download_test.go
  tools/testdata/test_tool_index.json
  v2/pkgs/pkgs.go
  v2/pkgs/testdata/test_tool_index.json
  v2/pkgs/tools.go
  v2/pkgs/tools_test.go
Labels: type: enhancement, topic: code, os: linux, os: macos, type: imperfection

#983 Improve `installed.json` handling in `v2/tools`
  tools/download.go
  tools/download_test.go
  tools/tools.go
  v2/pkgs/tools.go
Labels: type: enhancement, topic: code

#987 Insert lock while reading from the installed map
  v2/pkgs/tools.go
Labels: type: enhancement, topic: code

#990 Update `extract` to 4.0.0 and golang to 1.23
  .github/workflows/check-go-dependencies-task.yml
  .github/workflows/check-go-task.yml
  .github/workflows/publish-go-tester-task.yml
  .github/workflows/release.yml
  .github/workflows/test-go-integration-task.yml
  .github/workflows/test-go-task.yml
  .licenses/arduino-create-agent/go/github.com/codeclysm/extract/v4.dep.yml
  .licenses/arduino-create-agent/go/github.com/ulikunitz/xz.dep.yml
  .licenses/arduino-create-agent/go/github.com/ulikunitz/xz/internal/hash.dep.yml
  .licenses/arduino-create-agent/go/github.com/ulikunitz/xz/internal/xlog.dep.yml
  .licenses/arduino-create-agent/go/github.com/ulikunitz/xz/lzma.dep.yml
  .licenses/arduino-create-agent/go/golang.org/x/crypto/sha3.dep.yml
  go.mod
  go.sum
  updater/updater_darwin.go
  v2/pkgs/tools.go
Labels: topic: code, type: imperfection
