Repository arduino/arduino-create-agent, pull requests merged in 2024-03, with the labels that each got.

#909 Remove tests that cannot be run
  tests/test_update.py
Labels: topic: code, type: imperfection

#915 Add `register.arduino.cc` to the accepted extra origins
  main.go
Labels: type: enhancement, topic: code

#913 move Index init after reading the ini config
  main.go
Labels: topic: code, type: imperfection

#926 Add new items to the accepted CORS and remove `register.arduino.cc`
  main.go
Labels: type: enhancement, topic: infrastructure

#900 Implementation of port discovery through Pluggable discovery
  .licensed.yml
  .licenses/arduino-create-agent/go/github.com/arduino/arduino-cli/arduino/serialutils.dep.yml
  .licenses/arduino-create-agent/go/github.com/arduino/go-properties-orderedmap.dep.yml
  .licenses/arduino-create-agent/go/github.com/arduino/go-serial-utils.dep.yml
  .licenses/arduino-create-agent/go/github.com/arduino/pluggable-discovery-protocol-handler/v2.dep.yml
  .licenses/arduino-create-agent/go/github.com/leonelquinteros/gotext.dep.yml
  .licenses/arduino-create-agent/go/github.com/leonelquinteros/gotext/plurals.dep.yml
  conn.go
  go.mod
  go.sum
  hub.go
  main.go
  serial.go
  seriallist.go
  serialport.go
  upload/upload.go
Labels: type: enhancement, topic: code

#929 change label and url in the tray icon menu
  systray/systray_real.go
Labels: topic: code

#932 [skip-changelog] move tests using staging index to production one
  index/index_test.go
  main_test.go
  tools/tools.go
  v2/pkgs/tools_test.go
Labels: type: enhancement, topic: code
