Repository arduino/arduino-create-agent, pull requests merged in 2024-02, with the labels that each got.

#896 `agent-version.json` is pushed on downloads bucket now, and minor enhancements
  .github/workflows/release.yml
Labels: type: enhancement, topic: infrastructure

#897 Fix failure to execute tool post-install script on Windows
  tools/download.go
Labels: topic: code, os: windows, type: imperfection

#721 replace library used to interact with tray bar
  .github/workflows/publish-go-tester-task.yml
  .github/workflows/release.yml
  .github/workflows/test-go-integration-task.yml
  .github/workflows/test-go-task.yml
  .licenses/arduino-create-agent/go/fyne.io/systray.dep.yml
  .licenses/arduino-create-agent/go/fyne.io/systray/internal/generated/menu.dep.yml
  .licenses/arduino-create-agent/go/fyne.io/systray/internal/generated/notifier.dep.yml
  .licenses/arduino-create-agent/go/github.com/getlantern/errors.dep.yml
  .licenses/arduino-create-agent/go/github.com/getlantern/hex.dep.yml
  .licenses/arduino-create-agent/go/github.com/getlantern/ops.dep.yml
  .licenses/arduino-create-agent/go/github.com/getlantern/systray.dep.yml
  .licenses/arduino-create-agent/go/github.com/go-stack/stack.dep.yml
  .licenses/arduino-create-agent/go/github.com/godbus/dbus/v5.dep.yml
  .licenses/arduino-create-agent/go/github.com/godbus/dbus/v5/introspect.dep.yml
  .licenses/arduino-create-agent/go/github.com/godbus/dbus/v5/prop.dep.yml
  .licenses/arduino-create-agent/go/github.com/oxtoacart/bpool.dep.yml
  go.mod
  go.sum
  systray/systray_real.go
  tests/conftest.py
Labels: type: enhancement, topic: code

#905 Allow the user to specify `{fqbn}` parameter in the commandline
  upload/upload.go
  upload/upload_test.go
Labels: type: imperfection

#901 [skip-changelog] use OIDC to retrieve the credentials
  .github/workflows/release.yml
Labels: type: enhancement, topic: infrastructure

#906 [skip-changelog] fix release CI
  .github/workflows/release.yml
Labels: type: enhancement, topic: infrastructure
